### ISSUE TITLE
GDCMCONV not found

### ISSUE THREAD

**Issue by jdavidclares** [icometrix/dicom2nifti#11]
Hi! I'm trying to convert a DICOM directory to a nifti file with the function dicom2nifti.dicom_series_to_nifti but I always get this error: 
ConversionError: GDCMCONV_NOT_FOUND

Can anyone tell me the reason and how I can solve it? I really appreciate any help you can provide.

**Comment by abrys** [comment]
Hello,

First of all I would advise that you use either the command-line interface or "dicom2nifti.convert_directory" unless you are 100% certain that there is only one series in the directory.

About the error. This occurs when trying to convert compressed dicom files (jpeg, jpeg2000, ...) which are not natively supported. For this we use the gdcmconv command line tool. There are 2 ways to make it work. 
Install gdcmconv from libgdcm-tools (http://gdcm.sourceforge.net/wiki/index.php/Main_Page) and make certain it is globally from your path. 
Or install it and set the path to gdcmconv using "dicom2nifti.settings.set_gdcmconv_path(path)".

We will try to document these features a little better with a future release.

**Comment by normanius** [comment]
Just an alternative fix for that problem if one's working purely in a python environment: 

Install [Python-GDCM](https://pypi.org/project/python-gdcm/). It fixed the problem for me:

```bash
python -m pip install -U python-gdcm
```
