### ISSUE TITLE
Possibility for Community Maintenance

### ISSUE THREAD

**Issue by blakedewey** [icometrix/dicom2nifti#123]
There have been a lot of issues and pull requests here that go unanswered, but there are still commits made to the repository and releases are made. 

@abrys is there a possibility of adding to the maintenance community? I know I'd also like to see some different update/devops procedures to help keep track of changes. Currently, the releases and commits are very bare bones and it is very difficult to keep track.

**Comment by abrys** [comment]
As we use this in our clinical products we need to keep full control over the code. This does not mean that we don't accept pull requests etc but only if they fit our internal usage awel. 
The code is provided opensource in an effort to give back to the research community, however our first goal is still our own usage.
This will drive decisions on architecture, releases and time allocation to work on dicom2nifti.
