### ISSUE TITLE
Gray scale range seems to change when using the conversion function.

### ISSUE THREAD

**Issue by penguin1109** [icometrix/dicom2nifti#129]
Hello, I am currently working on a research project using full body ct/pet scans.
Your project was so helpful for the research, and I am very thankful for your work.

However, recently I have used the `dicom_series_to_nifti` function but realized that the gray scale range of the dicom file was from -1024, but the converted nifti file ranged from -3000 and below.
And the gray scale intensity contrast range changed simultaniously.

I cannot find the reason why, but this actually affects the result of the research quite much.

Will it be possible to you to give me some solutions for this problem, or at least some possible reasons for this?

Thank you so much.

**Comment by abrys** [comment]
Hello,

It indeed seems like the rescaling of the data is not handles correctly.

So either the data is missing some dicom headers (due to anonimization or so) or something is not correct for this type of data.
Is there a possibility to share a dataset with me so I can take a look? Without it, it will be guesswork and it will be very hard to fix the issue or point you into the correct direction in case something is wrong with the data itself.

Kind regards,
Arne Brys

**Comment by penguin1109** [comment]
Thanks for the quick reply!
However, I'm afraid the data is private, so I cannot share it in public - would it be possible to share it to you by email privately??

What kind of information in the dicom header do you think would be the cause???

**Comment by penguin1109** [comment]
Do you possibly think that the problem might be with the `.mim` file in each dicom series folder???

**Comment by abrys** [comment]
You could share it with me directly to arne.brys@icometrix.com. All data will be destroyed after figuring out the actual issue.
It would need to look into the Rescale Slope and Rescale Intercept etc in combination with the data. (see https://dicom.nema.org/medical/dicom/2018b/output/chtml/part03/sect_C.8.15.3.10.html)

**Comment by abrys** [comment]
When looking into a sample dataset shared with me it was clear that it is not an issue with dicom2nifti.
The very low values -3024 are already there in the dicom files. Everything outside of the FOV (circular on axial slices) is set to -3024.
For cases where this causes issues I suggest to do a simple post processing step using python.

`import nibabel
import numpy

def post_processing(input_nifti_file, output_nifti_file):
    # read the nifti using nibabel
    input_image = nibabel.load(input_nifti_file)
    # get the data from the nifti image
    input_data = numpy.asanyarray(input_image.dataobj)
    # update all values < -1024 to -1024
    input_data[input_data < -1024] = -1024
    # save the nifti again
    nibabel.Nifti1Image(input_data, input_image.affine).to_filename(output_nifti_file)


if __name__ == '__main__':
    post_processing(
        "some_directory/CT_3.nii.gz",
        "some_directory/CT_3_pp.nii.gz"
    )`
