### ISSUE TITLE
overflow for signed data where BitsStored is lower than BitsAllocated

### ISSUE THREAD

**Issue by abrys** [icometrix/dicom2nifti#13]
For some Hitachi mri data it became apparent that there is an overflow issue.
Some investigation lead to a but in pydicom where it does not seem to handle cases where bitsstored and bitsallocated do not match. The overflow occurs because the for example a 12 bit signed integer is stored in a 16 bit space. As the sign bit is the most significant bit (12) we cannot read this data as if it where 16 bits.

We should:
- Provide a workaround
- Report a bug with pydicom

**Comment by neurolabusc** [comment]
Are there any samples that are openly available. It would be great to include some of these with dcm_qa dataset so that different tools can be tested for compatibility.

**Comment by abrys** [comment]
We currently don't have any data available that can be shared. I am however currently in contact with a center that might be able to help us with that.
I'm searching for some anatomical, dti and fmri data that can be openly shared.

**Comment by abrys** [comment]
The fix made in 1.2.17 was a little shortsighted and was applying the patch to all data however it should only be done on signed data.
