### ISSUE TITLE
Issue working with multiple dicom series under a single folder

### ISSUE THREAD

**Issue by shrikanth95** [icometrix/dicom2nifti#132]
Hello,

Not sure if this is a bug. It looks like `convert_directory` ignores the additional dicom series. Is there is a way to automatically save the other series into different volumes? This is particularly useful when there are 4D (3D+t) volumes (such as in dynamic CTA and fMRI). I know the dcm2niix package does this but would be useful to have a python fix. I also looked up https://readthedocs.org/projects/dicom2nifti/downloads/pdf/latest/ and did not find a solution. 

As on now, using `convert_directory` only saves the first series in the directory with the file name provided by me. 

Thank you

**Comment by abrys** [comment]
Convert directory will split dicom files in the input directory using the series_instance_uid and generate one nifti for each series. In case of 4D data like fMRI or so it will generate 1 4D nifti.
