### ISSUE TITLE
Crash when some Dicom tag are empty(null)

### ISSUE THREAD

**Issue by namk-fc** [icometrix/dicom2nifti#135]
"convert_generic.py" Line: 69

If the value of tag(Dicom.RepetitionTime, Dicom.EchoTime) is empty(null), a flot-TypeError is thrown.
The following is a workaround try-except example.

    # Set TR and TE if available
    if Tag(0x0018, 0x0080) in dicom_input[0] and Tag(0x0018, 0x0081) in dicom_input[0]:
        try:
            common.set_tr_te(nii_image, float(dicom_input[0].RepetitionTime), float(dicom_input[0].EchoTime))
        except:
            ### TypeError: float() argument must be a string or a number, not 'NoneType'
            pass

**Comment by abrys** [comment]
Thanks for reporting.
We will fix this in the next release.

**Comment by abrys** [comment]
Will be fixed starting 2.4.9

**Comment by nourhanOfTerra** [comment]
Hello, I am still facing the same issue. Is there any solution?
