### ISSUE TITLE
Is there going to be a new version for python3?

### ISSUE THREAD

**Issue by ldelaoa** [icometrix/dicom2nifti#137]
I believe the installation using pip is only working with python 2.2.
Area there any plans of updating to python 3?

**Comment by abrys** [comment]
Unless you are trying to install a very old version of dicom2nifti installation should work under python3.
Even more, we have stopped supporting python 2 a long time ago.

Please check: https://pypi.org/project/dicom2nifti/ and the conda package https://anaconda.org/conda-forge/dicom2nifti/files

We are currently activaly using it with python version 3.8 to 3.10.
Potentially some other requirement is blocking the installation.

What OS are you trying to install on so we can try to reproduce the error.
