### ISSUE TITLE
Erro: module 'pydicom' has attribute 'read_file'. Version 3.0.0 broke things

### ISSUE THREAD

**Issue by Zhack47** [icometrix/dicom2nifti#148]
Thee following error arises since this morning and  the release of pydicom 3.0.0

![image](https://github.com/user-attachments/assets/a3ca7f3f-5a5c-4eba-bfbe-8d1308eb6955)

An easy fix is to  set the version pf pydicom to 2.4.4

Regards

**Comment by abrys** [comment]
Fixed support for pydicom >= 3.0.0 in release 2.5.0

**Comment by jdhenckel** [comment]
please accept my PR https://github.com/icometrix/dicom2nifti/pull/105 it is very important
