### ISSUE TITLE
dicom to nifti conversion (Philips) files not working 

### ISSUE THREAD

**Issue by jogachaganti** [icometrix/dicom2nifti#15]
the dicom2nifti guy is unable to convert the dicom rs fMRI file into Nifty (Philips) and this problem is not there for T-1 volumes. i am  not too sure what is the issue .
Can some one advice me please
Joga

**Comment by abrys** [comment]
Can you please provide more information:
- Version of dicom2nifti used
- Console output
- Type of philips data (multi-frame/enhanced dicom vs single-frame)

If possible provide some dicom data that has the issue.

**Comment by abrys** [comment]
Closing due to no feedback and no clear issue
