### ISSUE TITLE
AttributeError: Dataset does not have attribute 'SeriesNumber'.

### ISSUE THREAD

**Issue by varghesealex90** [icometrix/dicom2nifti#16]
Hi;

I am trying to convert a dcm file attained from TCIA. however I get the error AttributeError: Dataset does not have attribute 'SeriesNumber'.
. ANy work around for the same

**Comment by abrys** [comment]
In this case it seems like the deidentification method used to anonimize the data does not really follow the dicom standard as SeriesNumber is a type 2 field it should always be there. The issue only occurs when using the commandline version or convert_dir module as it is used to construct the filenames.

I made a small release (1.2.19) which removes the dependency on SeriesNumber and falls back to SeriesInstanceUID for the filenaming if series number is not there. If SeriesInstanceUID is not there then the sorting of the dicom files cannot work anyway so there is not issue on having a dependency here.

Please upgrade dicom2nifti to 1.2.19 or newer and try again
`pip install dicom2nifti>=1.2.19 --upgrade`
