### ISSUE TITLE
Warning:Assuming generic vendor conversion (ANATOMICAL)

### ISSUE THREAD

**Issue by shartoo** [icometrix/dicom2nifti#2]
This warning occur in some dicom directory,while others are ok. Can you  tell me what's wrong ?

**Comment by abrys** [comment]
The warning in this case means that it cannot identify it to one of the scanner manufacturers for which we have specific code.
These are GE, Siemens and Philips and are actually only used for more compex MR sequence types like fMRI and DTI.

This warning just states that it is falling back to the "generic" conversion. This should be fine for just about all anatomical images (most CT and MR images). 

Possible reasons you get the warning:
- Manufacturer (0x0008, 0x0070) field is missing or empty in the dicom headers
- The manufacturer is not GE, Siemens or Philips

Unless you are encountering other issues this should not impact your conversion at all.

Kind regards,
Arne

**Comment by shartoo** [comment]
Thank you for your patient answer,this project is pretty cool which make a complicated work simple and clear. The cause of error above was found that some slice  of a scan is missing,thank you once agagin!
