### ISSUE TITLE
Decompression Modifies Source File

### ISSUE THREAD

**Issue by cancan101** [icometrix/dicom2nifti#29]
This is generally a bad idea and fails on read only systems:
https://github.com/icometrix/dicom2nifti/blob/19961f8881a9111f23dc73aeb2851849021c7ea2/dicom2nifti/compressed_dicom.py#L122

**Comment by abrys** [comment]
Good point. The code originates from our private repositories where this never caused any issues but was migrated to dicom2nifti as it has a good use there. Merged in your pull request and should be in the next release
