### ISSUE TITLE
Logger changed with on import

### ISSUE THREAD

**Issue by cancan101** [icometrix/dicom2nifti#32]
Logger is changed on importing the module https://github.com/icometrix/dicom2nifti/blob/7e09afbeb44426aa27cf1b75be1ccf3cce2afdee/dicom2nifti/__init__.py#L30-L34.

This means that if I use `dicom2nifti` rather than running as a script, the logger is affected. Better would be to just set logger from runnable scripts.

**Comment by abrys** [comment]
Will move this to the script and our internal code

**Comment by abrys** [comment]
Fixed. Will be in the next release
