### ISSUE TITLE
make writing the output_file optional

### ISSUE THREAD

**Issue by satra** [icometrix/dicom2nifti#33]
for use in certain scenarios it would be great to just return the nibabel object instead of writing to a file.  perhaps the `output_file` can be turned into a keyword argument and if set to `None` will return an image rather than a path to a file.

**Comment by abrys** [comment]
Seems like a good idea. Will include it in the next release (cannot promise any date).

**Comment by abrys** [comment]
Implemented and will be in the next release

**Comment by satra** [comment]
@abrys - thank you.
