### ISSUE TITLE
investigate if we can also release to conda

### ISSUE THREAD

**Issue by abrys** [icometrix/dicom2nifti#35]
Don't know if it is possible as not all dependencies are available on conda

**Comment by abrys** [comment]
Don't know if it is possible as not all dependencies are available on conda

**Comment by abrys** [comment]
For now nibabel and pydicom do not have their packages on anaconda.org so the release to anaconda seems to be impossible for now

**Comment by yanrpi** [comment]
Both pydicom and nibabel are now available through conda-forge. Is it possible to put dicom2nifti also there?

https://anaconda.org/conda-forge/pydicom
https://anaconda.org/conda-forge/nibabel

**Comment by abrys** [comment]
As everything is now available and we have some time we will (attempt) add dicom2nifti to conda-forge

**Comment by abrys** [comment]
The review process on conda-forge is ongoing. We could have a working conda release in the next couple days

**Comment by abrys** [comment]
There is now a conda-forge package managed by us starting release 2.2.1
https://anaconda.org/conda-forge/dicom2nifti
