### ISSUE TITLE
Inconsistent slice increment

### ISSUE THREAD

**Issue by BBeuker** [icometrix/dicom2nifti#36]
I have a large group of DICOM series and due to some acquisition rounding errors two series have an inconsistent slice increment. Unfortunately, it is impossible for me to redo the acquisition so i was hoping i could fix it during the conversion. Is there any way to increase the error tolerance for the conversion?

Because it is probably introduced due to rounding the error is extremely small, so i would say it shouldn't really matter for the conversion.

**Comment by abrys** [comment]
I have a question for you.
Are you using dicom2nifti from command line or from python code.

If you are using it from code the slice increment consistency check can be disabled.
For now there is no option to do this from command line.
`import dicom2nifti
import dicom2nifti.settings as settings

settings. disable_validate_sliceincrement()

dicom2nifti.convert_directory(dicom_directory, output_folder)`

**Comment by koushika3** [comment]
I don't know how it was before but now it's settings. disable_validate_slice_increment().

**Comment by brangl** [comment]
Note the attribute has changed to 
settings.disable_validate_slice_increment() 
in the latest release - doesn't seem to be reflected in the docs yet.

**Comment by chaitanya-kolluru-elucid** [comment]
Is there a method in this library to transform the stack such that the slices are evenly spaced? 

I'm assuming toggling this validation simply ignores the issue.
