### ISSUE TITLE
Name of the files/hierarchy of the folder

### ISSUE THREAD

**Issue by samieti02** [icometrix/dicom2nifti#38]
Hello sir or madam,
thanks for the dicom2nifti.
I dont understand how the name of the generated nifti file is saved. When I open the data in RadiAnt oder ITK. I get this ONE "t1_mpr_ns_sag_K..RECO" . But when I use the code line with dicom2nifti.convert_directory, I get "21_tfl3d1_ns" which is the saved name of the file. I dont understand how it comes to this name??

Is there a function. if you want to save the nifti files like it was hierarchically defined in the folder
Meaning 
Folder A -> Folder A1: Dicom1
              -> Folder A2: Dicom2

And then in the code dicom2nifti.convert_directory(Folder A, Folder B), we have 

Folder B -> Folder A1: Nifti1
              -> Folder A2: Nifti2

Is it possible to keep this hierarchy?

Thanks

**Comment by abrys** [comment]
The naming is as followed:
- If SeriesDescription is present use SeriesNumber_SeriesDescription.nii.gz (starting dicom2nifti 2.0.3)
- Else If SequenceName is present use SeriesNumber_SequenceName.nii.gz 
- Else If ProtocolName is present use SeriesNumber_ProtocolName.nii.gz 
- Else fallback to SeriesNumber.nii.gz
