### ISSUE TITLE
Maybe convert_directory can return filename of created nifti?

### ISSUE THREAD

**Issue by joshy** [icometrix/dicom2nifti#40]
Hi,

thanks for dicom2nifti. I was wondering if you are considering changes for returning the filename of the created nifti file after calling `dicom2nifti.convert_directory`. My use-case is converting one directory with one series and I want to pass the nifti file reference to some other program for further processing. 

Thanks for your time,
Joshy

PS: I can also create a pull request if you want.

**Comment by abrys** [comment]
Hey,

This use-case is actually covered by code one lever deeper than convert_directory (however not documented).
In this case I would suggest converting in this way.
`from dicom2nifti.convert_dicom import dicom_series_to_nifti
dicom_series_to_nifti(dicom_directory, nifti_file)
`

So unless you need/want the automatic naming used in convert_directory I suggest using convert_dicom directly.
