### ISSUE TITLE
NamedTemporaryFile cannot be opened by gdcmconv on Windows

### ISSUE THREAD

**Issue by C-nit** [icometrix/dicom2nifti#46]
[tempfile.NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) used to store uncompressed dicom files (via `gdcmconv`) have a different behavior on Windows.

As the tmpfile is already open the subprocess trying to open it again fails.

It is an [open bug](https://bugs.python.org/issue14243) but has not received much attention. As of now it is expected behavior breaking dicom2nifti on Windows.

**Comment by abrys** [comment]
After a very long time I finally got round to setting up a windows test environment. Your changes has been integrated and will be available starting 2.2.2 (also on conda-forge).

**Comment by abrys** [comment]
2.2.2 was just released.
