### ISSUE TITLE
Looping through different dicom folder

### ISSUE THREAD

**Issue by abhinandanbatra** [icometrix/dicom2nifti#50]
**Hi, I am trying to loop through different folders of dicom data and convert them to nifti files. The code converts the first dicom folder to nifti but then throughs in an error (see below)*. if I try to do one folder at a time it works. Will really appreciate help  * 

Code:
`path=os.chdir('/Users/abhinandanbatra/Desktop/xxxx/xxxxx')
newpath='/Users/abhinandanbatra/Desktop/yyyy'
subfolders=os.listdir(path)
print(subfolders)
for f in subfolders:
      dicom2nifti.dicom_series_to_nifti(f, os.path.join(newpath,f+'_label'), reorient_nifti=True)`

Error:
> FileNotFoundError                         Traceback (most recent call last)
/anaconda3/lib/python3.7/site-packages/nibabel/loadsave.py in load(filename, **kwargs)
     39     try:
---> 40         stat_result = os.stat(filename)
     41     except OSError:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/abhinandanbatra/Desktop/pyradiomics/nifti/C6012011_label'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-57-95352681beb8> in <module>()
      7 for f in subfolders:
      8 #     dicom_input = dicom2nifti.common.read_dicom_directory(f)
----> 9     dicom2nifti.dicom_series_to_nifti(f, os.path.join(newpath,f+'_label'), reorient_nifti=True)
     10 #     if f.startswith('C6'):
     11 #         dicom2nifti.dicom_series_to_nifti(f, os.path.join(newpath,f+'_label'), reorient_nifti=True)

/anaconda3/lib/python3.7/site-packages/dicom2nifti/convert_dicom.py in dicom_series_to_nifti(original_dicom_directory, output_file, reorient_nifti)
     84         dicom_input = common.read_dicom_directory(dicom_directory)
     85 
---> 86         return dicom_array_to_nifti(dicom_input, output_file, reorient_nifti)
     87 
     88     except AttributeError as exception:

/anaconda3/lib/python3.7/site-packages/dicom2nifti/convert_dicom.py in dicom_array_to_nifti(dicom_list, output_file, reorient_nifti)
    144     # do image reorientation if needed
    145     if reorient_nifti:
--> 146         image_reorientation.reorient_image(results['NII_FILE'], results['NII_FILE'])
    147     return results
    148 

/anaconda3/lib/python3.7/site-packages/dicom2nifti/image_reorientation.py in reorient_image(input_image, output_image)
     29     # and get the image data in RAS orientation
     30     # print 'Reading nifti'
---> 31     image = load(input_image)
     32 
     33     # 4d have a different conversion to 3d

/anaconda3/lib/python3.7/site-packages/dicom2nifti/image_volume.py in load(nifti_file)
     41 
     42 def load(nifti_file):
---> 43     nifti_image = nibabel.load(nifti_file)
     44     return ImageVolume(nifti_image)
     45 

/anaconda3/lib/python3.7/site-packages/nibabel/loadsave.py in load(filename, **kwargs)
     40         stat_result = os.stat(filename)
     41     except OSError:
---> 42         raise FileNotFoundError("No such file or no access: '%s'" % filename)
     43     if stat_result.st_size <= 0:
     44         raise ImageFileError("Empty file: '%s'" % filename)

FileNotFoundError: No such file or no access: '/Users/abhinandanbatra/Desktop/pyradiomics/nifti/C6012011_label'

**Comment by TheGormlessGit** [comment]
I used to have an issue where dicom2nifti would try to convert files from os.listdir that have already been converted and therefore shouldn't appear in the list.

The basic solution I had was to move the DICOMs out one at a time to a separate folder using random.sample, and the conversion would take place in that folder. After conversion, the folder would be moved out just using shutil.move, and is marked with a prefix in the filename (which is removed before the script finishes) so it isn't re-converted.

Hope this helps a bit.

**Comment by abrys** [comment]
Hey,

I think the issue is actually that your not providing a valid filename to dicom_series_to_nifti.
The filename should have a .nii or .nii.gz extension as nibabel uses this to determine the way you write out the file
