### ISSUE TITLE
Resampling?

### ISSUE THREAD

**Issue by ujjwalbaid0408** [icometrix/dicom2nifti#56]
Can I resample the 3D brain MR data to 1mm*1mm*1mm? What is command for it?

**Comment by abrys** [comment]
We only implemented resampling for gantry tilted images to convert them to orthogonal images.
For resampling to a 1mm isotropic image I sugguest looking into the following options:
- Resample using scipy.ndimage.affine_transform (look at our resampling for the gantry tilted images for some input https://github.com/icometrix/dicom2nifti/blob/master/dicom2nifti/resample.py#L108)
- Resample using reg_resample (NiftyReg): some wrapper code will be needed to generate the reference image
- Resample using ResampleImage (Ants): https://github.com/ANTsX/ANTs/issues/388

Hope this is still helpfull.
