### ISSUE TITLE
Uncompressed nifti output

### ISSUE THREAD

**Issue by burns101** [icometrix/dicom2nifti#57]
just as the titles says, how can I get an uncompressed nifti output?

**Comment by abrys** [comment]
- In case you run from command line:
`dicom2nifti --no-compression ...`
- in case your run from python using dicom2nifti.convert_directory
`import dicom2nifti
dicom2nifti.convert_directory(dicom_directory, output_folder, compression=False)`
- in case you are using more direct conversion functions just provide a filename without .gz

For more information check the help
https://github.com/icometrix/dicom2nifti
