### ISSUE TITLE
BUG: output NIfTI image geometry inconsistent with the input DICOM series

### ISSUE THREAD

**Issue by fedorov** [icometrix/dicom2nifti#6]
Input test dataset (it is a time-resolved DCE acquisition): http://slicer.kitware.com/midas3/item/126198

Input dataset as visualized in 3D Slicer (http://slicer.org): 

![image](https://user-images.githubusercontent.com/313942/28592414-e183793e-7156-11e7-971c-beff57d9f2dc.png)

Result of dicom2nifti conversion as visualized in 3D Slicer (relative position preserved):

![image](https://user-images.githubusercontent.com/313942/28592424-ec8a8d36-7156-11e7-843c-62b2edcc5494.png)

**Comment by neurolabusc** [comment]
@fedorov - I am not familiar with Slicer, but everything looks fine to my eyes. The image below shows the raw DICOM loaded into Osirix and the converted NIfTI loaded into MRIcro. Note that the alignment matches and the bright spot is on the left. With Slicer it does not appear to rotate the NIfTI image to the nearest orthogonal, but if you load the render view you can see from the balls that the coordinates appear fine. The default coordinate for DICOM is to have rows go from top-to-bottom, the way you read english, whereas the default with NIfTI is to have the rows ascend with larger values further up the Y axis from relative to smaller values, the way you would draw a graph with cartesian coordinates. The good news is that the precise rotation is stored in the SForm of the NIfTI header, so while it is appropriate to reverse the row order between formats the final image stores this information. 
  https://www.slicer.org/wiki/Coordinate_systems
Perhaps you could add a feature request for Slicer to have the ability to load images in a default format. For example, the code below losslessly reorients a volume to match the nearest orthogonal to an identity matrix and then saves the residual rotation in the matrix. This ensures that images appear roughly aligned without interpolation and retaining rotation information.
  https://github.com/neurolabusc/MRIcro/blob/1bb6fa088a0ec61bbdd93f89b1c0c54677b0bc76/MRIcroX/nii_ortho.cpp


![simple](https://user-images.githubusercontent.com/8930807/28595672-d8762eac-7162-11e7-9010-a7f0a770ae16.jpg)

**Comment by fedorov** [comment]
@neurolabusc you can only evaluate whether orientation is preserved if you load both the original dataset and the converted NIFTI dataset into the same system, which I did.

Any system that completely ignores anatomic orientation will show both image volumes in an identical way.

**Comment by fedorov** [comment]
Also note that if I manually separate the frames corresponding to the first time point in that DCE acquisition, the resulting NIFTI dataset has orientation consistent with the source DICOM, as viewed in Slicer. 

For your convenience, here you go:  [1frame.zip](https://github.com/icometrix/dicom2nifti/files/1174907/1frame.zip)

**Comment by neurolabusc** [comment]
Again, I am not familiar with Slicer, but Osirix (DICOM) and MRIcro/SPM (NIfTI) agree that coordinates work out. Likewise in Slicer the bright spot is in the left (bright purple) side. The NIfTI/MNI coordinates are ascending from L->R and P->A, while the reverse is true in the DICOM coordinates.

**Comment by neurolabusc** [comment]
I would be cautious with piping 2D DICOM slices through standard DICOM to NIfTI conversion. Beyond the slice thickness problems you previously mentioned, the depth is usually computed as the cross-product of the row and column vectors, so the polarity is ambiguous. While viewing a single slice makes sense, one does not know the depth direction. In other words, are you viewing a slice from radiological (foot/anterior) or neurological (head/posterior) direction. I think this figure shows the issue
 https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage#Neurological_versus_radiological_convention

It seems like there should be simple solution, but as I recall the way different vendors have implemented this makes it tricky.

**Comment by fedorov** [comment]
> Again, I am not familiar with Slicer, but Osirix (DICOM) and MRIcro/SPM (NIfTI) agree that coordinates work out.

Alright, then there must be a bug in either ITK or Slicer. But this is a corner case, and I don't have cycles to investigate this.

> I would be cautious with piping 2D DICOM slices through standard DICOM to NIfTI conversion. 

I did not try that. What I did is separate the spatially consecutive slices corresponding to the first time-point of a temporal DCE acquisition, and pass the directory (which I attached earlier) with those slices to dicom2nifti. The resulting nifti volume had orientation consistent with DICOM, as displayed in Slicer. It appears that something goes haywire somewhere when dicom2nifti tries to process a series that is a temporally resolved acquisition. 

I do not know if dicom2nifti is expected to handle a temporally resolved 3d series, and if yes - what is expected as a result.

**Comment by neurolabusc** [comment]
Sounds reasonable. One issue with that scan is that it is not acquired orthogonal to the scanner bore, so I am not sure how Slicer chooses its representative slice, but that might be an issue. It does make it hard when you have two coordinate systems with opposite polarities for some dimensions and are viewing an oblique slice. One suggestion for moving forward is to examine the behavior of dicom2nifti with small dataset that has clearly identified fiducial markers. For example, this dataset includes fiducial markers with axial, coronal and sagittal acquisitions:
  https://github.com/neurolabusc/dcm_qa
be aware that the later volumes have intentional head motion
  http://www.mccauslandcenter.sc.edu/crnl/tools/stc
I have to say that in my limited testing I have been really impressed with dicom2nifti.

**Comment by fedorov** [comment]
@neurolabusc I think the reason I am being a troublemaker here is I am not a neuroimaging person, so the types of data I am trying to apply dicom2nifti are very different from what was tested. It looks like this tool was developed by neuroimaging people (and I gather from your name, you are also one of "them" ;-). I hope it can be useful to non-neuroimaging people as well - it would be very nice to have such a universal conversion tool available.

**Comment by neurolabusc** [comment]
I agree it is confusing. Just remember that space is defined as LPS in DICOM and RAS in NIfTI/MNI/Talairach (e.g. the X coordinate increases as you go leftward in DICOM, but increases as you go rightward in NIfTI). 
  https://www.slicer.org/wiki/Coordinate_systems
A nice analogy would be the way one reads English versus Hebrew text. While both DICOM and NIfTI are explicit, they are different. @abrys you can close this issue.

**Comment by abrys** [comment]
Thanks for looking into this closer. Will close the issue.

**Comment by fedorov** [comment]
@abrys what is the expected output of the converter when the input is a time-resolved series?

**Comment by neurolabusc** [comment]
The [NIFTI format](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) is very explicit about this. Specifically `dimensions  1,2,3 for space (x,y,z), 4 for time (t), and 5,6,7 for anything else needed.` Therefore, if you look at a 2D image across time fslhd will report dims 1..4 as X,Y,1,T. On the other hand, a 3D volume across time (e.g. fMRI time series) will be X,Y,Z,T. In theory, diffusion datasets with different gradient directions (D) should be saved as X,Y,Z,1,D. In practice, the available tools save diffusion data as X,Y,Z,D (a violation of the strict NIfTI definitions). Another issue is how to save images with multiple echoes or data where each channel of the coil saves a different spatial image. One option is to use the dimensions 5..7 to encode this. This is valid, but most tools do not know how to distinguish more than 4 dimensions in one file. For [dcm2niix](https://github.com/rordenlab/dcm2niix) I save each of these as a separate file (e.g. "e2" means 2nd echo and "c2" means second channel).

**Comment by neurolabusc** [comment]
@fedorov I did update the [dcm2niix wiki](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates) to help clarify the differences between the DICOM and NIfTI coordinates. As an advanced comment, in future DICOM to NIfTI converters should probably deal with the fact that DICOM coordinates are different for bipeds versus quadrupeds as specified by [0010,2210](ftp://dicom.nema.org/MEDICAL/dicom/2015b/output/chtml/part03/sect_C.7.6.2.html#sect_C.7.6.2.1.1).
