### ISSUE TITLE
AttributeError: module 'dicom2nifti' has no attribute 'convert_directory'

### ISSUE THREAD

**Issue by Julio-A-Yanes** [icometrix/dicom2nifti#63]
I'm trying to convert a dicom directory to nifti. Just pip installed dicom2nifti this morning. Following code produces "AttributeError: module 'dicom2nifti' has no attribute 'convert_directory'" running Python 3.7.1.

import dicom2nifti

dicom_directory = ('/Volumes/Yanes_External/Data/Yanes_Dissertation/YD_P5_H7T191115-JAY01/YANES_F31_20191115_163844_406000/T1_MPRAGE_1ISO_SAG_P2_AA_0006')
output_folder = ('/Users/julioyanes/Desktop/P05/FT')

dicom2nifti.convert_directory(dicom_directory, output_folder, compression=True, reorient=True)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-ecd41895faf5> in <module>
----> 1 dicom2nifti.convert_directory(dicom_directory, output_folder, compression=True, reorient=True)

AttributeError: module 'dicom2nifti' has no attribute 'convert_directory'
---------------------------------------------------------------------------

Any ideas?

**Comment by abrys** [comment]
Can you please provide me the output for the following.
`import dicom2nifti
dicom2nifti.__file__`

**Comment by abrys** [comment]
Closed due to inactivity
