### ISSUE TITLE
Orthogonal resampling

### ISSUE THREAD

**Issue by ryan102590** [icometrix/dicom2nifti#64]
When I resample my dicoms to orthogonalize them they are being inverted upside down despite direction changes being turned off.

**Comment by abrys** [comment]
When resampling to orthogonal space the reorient image is implicitly done as it would become exponentially more complex to try to keep the original orientation.
However the image is not inverted (if you properly take into account the affine matrix). We just make the images consistent in orientation.

The documentation will be updated so this is clear.
