### ISSUE TITLE
Documentation error in dicom2nitfi.settings

### ISSUE THREAD

**Issue by annikaliebgott** [icometrix/dicom2nifti#66]
Hi there, I just noticed that your documentation has a tiny (probably spelling)error regarding the possibility to disable the slice increment validation:

In settings.py, you define the function as disable_validate_**slice_increment**(), but in the documentation it's disable_validate_**sliceincrement**()

Just wanted to let you know because I was a little confused when I first got the resulting "has no attribute" error and it took me quite a while to notice the difference :-)

**Comment by abrys** [comment]
Thanks for letting us know. I am working on updating the documentation anyway so it should be updated in the near future.
