### ISSUE TITLE
Conversion process should not rely on InstanceNumber 

### ISSUE THREAD

**Issue by fedorov** [icometrix/dicom2nifti#7]
Problem 1: `InstanceNumber` is Type 2 attribute - it can be missing. As of current version of dicom2nifti, missing `InstanceNumber` results in no output produced.

Problem 2: There is also no hard rule that requires InstanceNumber to establish the spatial ordering of the frames. The only reliable way to sort instances and reconstruct volume is to sort them using `Image Position (Patient)` and `Image Orientation (Patient)` (also see related discussion in http://dclunie.blogspot.com/2013/10/how-thick-am-i-sad-story-of-lonely-slice.html), and this approach is currently not implemented in the tool.

Speaking for myself, until this issue is resolved, it is hard to seriously consider using dicom2nifti.

**Comment by abrys** [comment]
We will try to resolve the issue however in the next release.

**Comment by abrys** [comment]
Removed the dependency as much as possible.
For normal anatomical data there should be no dependency.
For some mri sequences this was not possible however as it is required for mri this should not be an issue for now http://dicomlookup.com/lookup.asp?sw=Ttable&q=C.8.13-3

**Comment by fedorov** [comment]
Thanks for the update!

> For some mri sequences this was not possible however as it is required for mri this should not be an issue for now http://dicomlookup.com/lookup.asp?sw=Ttable&q=C.8.13-3

I think the table you mentioned applies to Enhanced MR IOD. I did not find the table with exact same number in the official standard, but section C.8.13 is _Enhanced MR Image_, and the closest table I could find is this one:
 http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.13.2.html. I still do not see evidence that you can rely on InstanceNumber to be present in the input dataset.
