### ISSUE TITLE
Multi-Echo MPRAGE

### ISSUE THREAD

**Issue by erikglee** [icometrix/dicom2nifti#70]
Hi, 

I am just trying out your tool and wanted to report an issue I have had. I have the dicoms for a Siemens Multi-Echo MPRAGE file that has 960 files (192/echo). When I try to use the "dicom_series_to_nifti" command to convert these, I receive an error regarding the slice increment. Then, when I disable the validation of slice increment, the nifti file that is made from the function has the slices from the 5 different echos stacked so that instead of me getting a 256x256x192x5 image I get a 256x256x960 image.

I would share the image I am working with, but unfortunately it is not mine to share.

Thanks!
Erik

**Comment by abrys** [comment]
Hey Erik,

I think I know what is happening here. It is not being detected as a 4D image and thus trying to convert it as a single 3D stack causing the other checks to fail. It assume it would be quite simple to fix this type of issue however I would need some data for this. So if you have have any idea of an open example of this type of data or you could provide an anonymised version of such dataset it would be great. Can even be of a phantom or with the pixel data scrambeled.

**Comment by abrys** [comment]
For now it seems like I was able to locate some data that we can use. So I might be able to fix this and ask you to test with your data to see if you achieve the desired result

**Comment by erikglee** [comment]
Thanks! Yes I would be happy to test this after said update.

**Comment by abrys** [comment]
Please install 2.2.6 using conda or pip and test it again.

**Comment by erikglee** [comment]
Works perfect now, thanks!
