### ISSUE TITLE
Exceptions should be raised not just print in console

### ISSUE THREAD

**Issue by GJChen919** [icometrix/dicom2nifti#74]
Hi all:
I think all the exceptions should be raised that user can handle it not just printed by logger.
I found these codes at line:66-67, 98-99, 153-154 in dicom2nifti.convert_dir module.
I pushed the fixed code to [my repository](https://github.com/GJChen919/fixs/blob/master/convert_dir_fix.py).

hope developers can fix it, thanks.
And if OK I want to join you all to maintain the developing jobs.

**Comment by abrys** [comment]
As explained in the comments of the except this is intended behaviour. The convert_dir module explicitly does this to convert as many series in a folder that it can thus it should not stop at the first error it occurs.

If you need more control please use convert_dicom.dicom_series_to_nifti as this will raise exceptions as needed.
It does however require dicom files to be sorted per series.

About helping in the development. As icometrix uses dicom2nifti in multiple clinical devices / clinically used products we keep all development of dicom2nifit in house, however keep dicom2nifti available opensource. So the help in the development we can only accept pull requests on existing issues.
