### ISSUE TITLE
No file is produced

### ISSUE THREAD

**Issue by wanderine** [icometrix/dicom2nifti#80]
I am using dicom2nifti through python but no nifti file is produced and no error is given?

dicom2nifti.convert_directory('/raid/andek67/nnunetdocker/testdicom/NSCLC-RADIOMICS-INTEROBSERVER1/interobs06/02-18-2019-CT-43086/01133/','/raid/andek67/nnunetdocker/testoutput2')

The directory 

/raid/andek67/nnunetdocker/testdicom/NSCLC-RADIOMICS-INTEROBSERVER1/interobs06/02-18-2019-CT-43086/01133/

contains 178 Dicom files

**Comment by abrys** [comment]
Depending on what you want to do convert_directory might not be the best solution here as this mainly exitst for the command line tool to read a complete directory (study containing multiple series) and convert as many as possible. It suppresses errors and will use the python logging framework to print the errors. You do however need to setup the logging framework similar to https://github.com/icometrix/dicom2nifti/blob/master/scripts/dicom2nifti#L16-L20.

In a more typical use case i would sugguest using `dicom2nifti.convert_dicom.dicom_series_to_nifti`
This does however require the directory to only contain 1 series not a complete study.
