### ISSUE TITLE
xyzt_units?

### ISSUE THREAD

**Issue by ivantarapov** [icometrix/dicom2nifti#82]
I have noticed that files produced by the conversion have xyzt_units set to the default of 0 (units unknown). I didn't spot any code in the repo that would set this value. Is this by design? 

Can't we assume that DICOM would always use mm and thus always set xyzt_units to 2 (mm) in the header?

**Comment by abrys** [comment]
We implemented this change setting the units for xyz to 2 (mm) t remains unknown.
It will be included in the next release (probably in a few days)
Thanks for the suggestion.
