### ISSUE TITLE
dicom2nifti.exceptions.ConversionError: NOT_A_VOLUME

### ISSUE THREAD

**Issue by SYSUMSD** [icometrix/dicom2nifti#86]
I have some dicom files and try to transform them to nifti files. I am a green hand to this field....
These files include heart short-axis MRI photos with about 200*200 matrix , 13 slices and 50 time frames using siemens healthcare equipments. So this directory has 13*50 dicom files.  I want to transform them to nifti format.
But when I ran dicom2nifti.dicom_series_to_nifti function(I have moved individual MRI dicom files  within a series(slice) to a new directory before using this function. So the new directory has 50 dicom files ). I met this error:`dicom2nifti.exceptions.ConversionError: NOT_A_VOLUME`
And when I ran dicom2nifti. convert_directory function I met the same error.
How to use these functions correctly? Can you offer me more detail?

**Comment by abrys** [comment]
The NOT_A_VOLUME exception occurs when all slices in the series have the same image position patient.
As this would be a more exotic case it might just be that we do not fully support it yet however I would assume this would be similar to for example brain fMRI.

If you would be able to provide me with an anonymous example dataset that has this issue I might be able to add support for this.

**Comment by SYSUMSD** [comment]
Sorry， the dataset manages don't allow me to offer these data to others...
I'll try other methods...
Thanks for your help!

**Comment by abrys** [comment]
No problem,
Should you encounter a similar dataset that can be shared just reopen the issue and we might be able to implement support.
