### ISSUE TITLE
single slice conversion

### ISSUE THREAD

**Issue by bkonk** [icometrix/dicom2nifti#88]
is there a way to run dicom to nifti conversion on a single dicom file containing a single slice?

thanks

**Comment by abrys** [comment]
Currently dicom2nifti does not support single slice conversion due to the additional validation check that make some assumptions on the amount of slices. Some small changes would make this possible.
Will try to build a new release including support soon.

**Comment by abrys** [comment]
Starting the 2.2.12 release you can do single slice conversion.
See the single slice examples in the readme section on https://github.com/icometrix/dicom2nifti

**Comment by bkonk** [comment]
Terrific, thank you!
